export { default as ExplorePage } from './Explore'
export { default as VideoPage } from './Video'
export { default as EditPage } from './Edit'
export { default as ToolsPage } from './Tools'
export { default as CategoryPage } from './Category'
export { default as RemixPage } from './Remix'
